export const API_REQUEST = 'API_REQUEST';
export const API_FINISH = 'API_FINISH';
export const API_ERROR = 'API_ERROR';

export const GET_API_CONFIG = 'GET_API_CONFIG';

export const GET_MOVIES_POPULAR = 'GET_MOVIES_POPULAR';
export const GET_MOVIES_NOW_PLAYING = 'GET_MOVIES_NOW_PLAYING';
export const GET_MOVIES_UPCOMING = 'GET_MOVIES_UPCOMING';
export const GET_MOVIES_DETAILS = 'GET_MOVIES_DETAILS';
export const GET_MOVIES_DISCOVER = 'GET_MOVIES_DISCOVER';
export const GET_MOVIES_DISCOVER_TOP = 'GET_MOVIES_DISCOVER_TOP';
export const GET_MOVIES_DISCOVER_UPCOMING = 'GET_MOVIES_DISCOVER_UPCOMING';

export const GET_TV_POPULAR = 'GET_TV_POPULAR';
export const GET_TV_DETAILS = 'GET_TV_DETAILS';
export const GET_TV_DISCOVER = 'GET_TV_DISCOVER';
export const GET_TV_DISCOVER_TOP = 'GET_TV_DISCOVER_TOP';

export const GET_PERSON_DETAILS = 'GET_PERSON_DETAILS';

export const GET_SEARCH_PERSON = 'GET_SEARCH_PERSON';
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';
export const GET_SEARCH_TV = 'GET_SEARCH_TV';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

export const CLEAR_STORE_STATE = 'CLEAR_STORE_STATE'