export const API_REQUEST = 'API_REQUEST';
export const API_FINISH = 'API_FINISH';
export const API_ERROR = 'API_ERROR';

export const GET_API_CONFIG = 'GET_API_CONFIG';

export const GET_MOVIES_POPULAR = 'GET_MOVIES_POPULAR';
export const GET_MOVIES_NOW_PLAYING = 'GET_MOVIES_NOW_PLAYING';
export const GET_MOVIES_UPCOMING = 'GET_MOVIES_UPCOMING';
